# Generated by Django 5.1.1 on 2024-09-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='subcontent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='subimg',
            field=models.ImageField(blank=True, null=True, upload_to='blog-images/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
